### PR TITLE
Updated to use percentages

### PR DESCRIPTION
**Pull request by arcidias**
Updated to use percentages instead of fixed numbers.
Also added warning and critical threshold to output, for information

### CODE REVIEW

**Comment by arcidias** [comment]
@psi-4ward I really like your solution for btrfs monitoring! For my own purposes I decided to use percentage out of the total space for warning and critical alarms. Also added the threshold values in the output for better viewing. If you like them, merge them :)

Here's also some output:
```
./check_btrfs_usage.sh -m / -w 10 -c 5
Free: 367423MB
Warning threshold: 38436MB
Critical threshold: 19218MB
Used: 16937MB
 | Used=16937MB;0;0;0;384360 Free=367423MB;10;5;384360;0
```

**Comment by psi-4ward** [comment]
good point but can we hide this using a flag to not break the compatibility?

**Comment by psi-4ward** [comment]
our you set warn/crit with a `%` sign

**Comment by arcidias** [comment]
Fair enough, will do and update PR

**Comment by arcidias** [comment]
@psi-4ward how about this?

Here's output:

```
# ./check_btrfs_usage.sh -m / -c 5% -w 10%
Free: 367419MB
Warning threshold: 38436MB
Critical threshold: 19218MB
Used: 16941MB
 | Used=16941MB;0;0;0;384360   Free=367419MB;10;5;384360;0

# ./check_btrfs_usage.sh -m / -c 5000 -w 10000
Free: 367419MiB
Warning threshold: 10000MB
Critical threshold: 5000MB
Used: 16941MB
 | Used=16941MB;0;0;0;384360 Free=367419MB;10000;5000;384360;0

# ./check_btrfs_usage.sh
Free: 367419MiB
Warning threshold: 10000MB
Critical threshold: 5000MB
Used: 16941MB
 | Used=16941MB;0;0;0;384360 Free=367419MB;10000;5000;384360;0


# ./check_btrfs_usage.sh -h
btrfs filesystem usage monitoring plugin
https://github.com/psi-4ward/check_btrfs_usage

Usage: ./check_btrfs_usage.sh <options>
  -m <mount>    Mountpoint of btrfs filesystem (default: /)
  -w <warn>     Warning when estimated free space is below MiB (default 10000). Add % at the end to define in percentage value. Must be used the same way as crit value.
  -c <crit>     Critical when estimated free space is below MiB (default 5000). Add % at the end to define in percentage value. Must be used the same way as warn value.
```

**Pull request merged**
